version: "3"

services:
  
  hub:
    
    image: selenium/hub:4.7
    
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
  chrome:
    shm_size: 1gb
    depends_on:
      - hub
    image: selenium/node-chrome:4.7
    environment:
      - SE_EVENT_BUS_HOST=hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    volumes:
      - ./downloads:/home/seluser/Downloads
  firefox:
    shm_size: 1gb
    depends_on:
      - hub
    image: selenium/node-firefox:4.7
    environment:
      - SE_EVENT_BUS_HOST=hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    volumes:
      - ./downloads:/home/seluser/Downloads
  search-moduleF:
    image: vonsdpcker/selenium-docker
    depends_on:
      - chrome
      - firefox
    environment:
      - BROWSER=firefox
      - HUB_HOST=hub
      - MODULE=search-module.xml
    volumes:
      - ./output/search-resultsF:/usr/share/udemy/test-output
  search-moduleC:
    image: vonsdpcker/selenium-docker
    depends_on:
      - chrome
      - firefox
    environment:
      - BROWSER=firefox
      - HUB_HOST=hub
      - MODULE=search-module.xml
    volumes:
      - ./output/search-resultsC:/usr/share/udemy/test-output
  book-moduleC:
    image: vonsdpcker/selenium-docker
    depends_on:
      - chrome
      - firefox
    environment:
      - BROWSER=chrome
      - HUB_HOST=hub
      - MODULE=testnj.xml
    volumes:
      - ./output/book-resultsC:/usr/share/udemy/test-output
  book-moduleF:
    image: vonsdpcker/selenium-docker
    depends_on:
      - chrome
      - firefox
    environment:
      - BROWSER=chrome
      - HUB_HOST=hub
      - MODULE=testnj.xml
    volumes:
      - ./output/book-resultsF:/usr/share/udemy/test-output
